name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry install

    - name: Run linting
      run: |
        poetry run flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
        poetry run pylint service tests --max-line-length=127

    - name: Run tests
      run: |
        poetry run pytest --pspec --cov=service --cov-fail-under=95

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true